on:
    push:
        branches:
            - main
jobs:
    context-job:
        runs-on: ubuntu-latest
        steps:
            - name: repo and author
              run: "echo repo: ${{github.repository}} by ${{github.actor}}"
            - name: show complete env context
              run: echo " ${{ toJson(github) }}"
            - name: show complete env context
              run: echo " ${{ toJson(env) }}"