on:
    push:
        branches:
            - main

jobs:
    vars-job:
        runs-on: ubuntu-latest
        steps:
            - name: print vars
              run: echo 'group= ${{ vars.GROUP_NAME}} user = ${{ vars.USER_NAME}} secret =${{ secrets.TOKEN}}'